"""
Train a YOLOv8n detector for danger sign localization.

Uses ultralytics API with a YOLO-format dataset generated by build_yolo_dataset.py.
The trained model is saved as an ultralytics-native checkpoint.

Example:
    python model/train_yolo.py --epochs 50 --device cpu
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from model.constants import DEFAULT_YOLO_ARTIFACT, DEFAULT_YOLO_DATASET_DIR  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train YOLOv8n danger sign detector")
    parser.add_argument("--data", type=Path, default=DEFAULT_YOLO_DATASET_DIR / "dataset.yaml")
    parser.add_argument("--out", type=Path, default=DEFAULT_YOLO_ARTIFACT.parent)
    parser.add_argument("--model", type=str, default="yolov8n.pt",
                        help="Pretrained YOLO base model")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--image-size", type=int, default=640)
    parser.add_argument("--device", type=str, default="auto",
                        help="auto (MPS/CUDA/CPU), mps, cuda, cpu")
    parser.add_argument("--patience", type=int, default=20)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--workers", type=int, default=0)
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not args.data.exists():
        print(f"错误: 数据集配置不存在: {args.data}")
        print("请先运行: python model/build_yolo_dataset.py")
        sys.exit(1)

    import torch
    from ultralytics import YOLO

    if args.device == "auto":
        if torch.backends.mps.is_available():
            args.device = "mps"
        elif torch.cuda.is_available():
            args.device = "cuda"
        else:
            args.device = "cpu"

    print(f"加载预训练模型: {args.model}")
    model = YOLO(args.model)

    run_dir = args.out / "yolo_runs"
    run_dir.mkdir(parents=True, exist_ok=True)

    print(f"开始训练: epochs={args.epochs}  batch={args.batch_size}  device={args.device}")
    model.train(
        data=str(args.data),
        epochs=args.epochs,
        batch=args.batch_size,
        imgsz=args.image_size,
        device=args.device,
        patience=args.patience,
        seed=args.seed,
        workers=args.workers,
        project=str(run_dir),
        name="train",
        exist_ok=True,
    )

    best_src = run_dir / "train" / "weights" / "best.pt"
    dest = args.out / "yolo_detector.pt"
    if best_src.exists():
        shutil.copy2(best_src, dest)
        print(f"最佳模型已保存: {dest}")
    else:
        last_src = run_dir / "train" / "weights" / "last.pt"
        if last_src.exists():
            shutil.copy2(last_src, dest)
            print(f"最终模型已保存 (无 best): {dest}")
        else:
            print("警告: 未找到训练产生的权重文件")


if __name__ == "__main__":
    main()
